Add cb in removeOutgoingMessage function arg
cb was missing in the removeOutgoingMessage which threw the below:

cb(new Error('Message removed'))
    ^

TypeError: cb is not a function